requirejs.config({
	paths:{
		"jquery":"scripts/jquery-3.2.1",
		"cookie":"scripts/jquery.cookie",
		"magn":"scripts/magn",
		"map":"scripts/map",
		"verification":"scripts/verification",
		"num":"scripts/detailnum",
		"val":"scripts/validation",
		"form":"scripts/form",
		"scroll":"scripts/magnscroll",
		"paging":"scripts/paging",
		"over":"scripts/over",
		"overnav":"scripts/overnav",
		"overGoodsCarTop":"scripts/overGoodsCarTop",
		"tab":"scripts/tab",
		"search":"scripts/search",
		"scroll":"scripts/scroll",
		"sidePanel":"scripts/sidePanel",
		"brand":"scripts/brand",
		"foodscar":"scripts/foodscar"
	}
})